class types :
    HSM_REQ_DISTI_AUTH= "HSM_REQ_DISTI_AUTH"
    DISTI_AUTH_HSM= "DISTI_AUTH_HSM"
    HSM_REQ_CY_AUTH= "HSM_REQ_CY_AUTH"
    CY_AUTH_HSM= "CY_AUTH_HSM"
    HSM_SIGNING_KEY_PKG= "HSM_SIGNING_KEY_PKG"
    OEM_ROT_AUTH= "OEM_ROT_AUTH"
    OEM_ROT_AUTH_PKG= "OEM_ROT_AUTH_PKG"
    OEM_PROV_REQ= "OEM_PROV_REQ"
    DISTI_PROV_AUTH= "DISTI_PROV_AUTH"
    CY_DEV_ID= "CY_DEV_ID"
    HSM_ROT_CMD= "HSM_ROT_CMD"
    HSM_PROV_CMD= "HSM_PROV_CMD"
    